# Generated by Django 5.0 on 2023-12-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='picture_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
