# Generated by Django 5.0 on 2023-12-28 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_items_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='selling', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
