# Generated by Django 5.0 on 2023-12-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_items_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='date',
            field=models.DateField(default='2023-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='time',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
