# Generated by Django 5.0 on 2023-12-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_items_date_items_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='time',
            field=models.TimeField(),
        ),
    ]
