# Generated by Django 5.0 on 2023-12-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(default='other', max_length=100),
            preserve_default=False,
        ),
    ]
