# Generated by Django 5.0 on 2023-12-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('digital', 'Digital services'), ('cosmetics', 'Cosmetics and body care'), ('food', 'Food and beverage'), ('furniture', 'Furniture and decor'), ('health', 'Health and wellness'), ('household', 'Household items'), ('other', 'Other')], max_length=100),
        ),
    ]
