# Generated by Django 5.0 on 2024-01-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_items_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlsit',
            field=models.ManyToManyField(blank=True, null=True, related_name='interested_people', to='auctions.items'),
        ),
    ]
