# Generated by Django 5.0 on 2024-01-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_watchlsit_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='current_bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
