# Generated by Django 5.0 on 2024-01-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
