# Generated by Django 5.0 on 2024-01-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_items_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='auctions.comment'),
        ),
    ]
